### DISCUSSION TITLE
Parameters usage in bash script

### DISCUSSION THREAD

**Discussion by dauphinpasdroit** [gocd/gocd#11867] [Q&A] [answered]
Hello,

I encountered an issue regarding the parameters usage into a bash script.

First, here is the configuration pipeline file:

```
format_version: 10
pipelines:
  windowsAzure:
    group: serverDeployment
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: <<redacted>>
        shallow_clone: false
        auto_update: false
        branch: main
    stages:  
    - preconfig:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          preConfig:
            elastic_profile_id: eaProd
            tasks:
            - exec:
                command: /bin/bash          
                arguments: 
                - ./pipelines/deployVm/windowsAzure/jobs/preConfig/preConfig.sh
                run_if: passed
    - infrastructureDeployment:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          infrastructureDeployment:
            elastic_profile_id: eaProd
            tasks:
            - exec:
                command: /bin/bash          
                arguments: 
                - ./pipelines/deployVm/windowsAzure/jobs/infrastructureDeployment/terraform.sh
                run_if: passed
    parameters:
      region: ""
      vm_size: ""
      domain_name: ""
      packer_image: ""
      azure_location: ""
      affiliate: "MEA"
      server_role: "APP"
      environment: "PROD"
      snakeid: ""
      patching: ""
      monitoring_emea: ""
      application: "GoCD"
      backup_policy: ""
      subscription: ""
```

And here is the bash script I use in the first job (```preconfig```):

```
#!/bin/bash
echo #{affiliate}
APPLI=${#{application}// /-}
az login --service-principal -u ${ARM_CLIENT_ID} -p ${ARM_CLIENT_SECRET} --tenant ${ARM_TENANT_ID}
az account set --subscription ${ARM_SUBSCRIPTION_ID}
az group create -l ${AZURE_LOCATION} -n "{affiliate}-{APPLI^^}-{ENVIRONMENT^^}"
ansible-galaxy collection install netbox.netbox
ansible-galaxy collection install azure.azcollection
python3 ./pipelines/deployVm/windowsAzure/jobs/preConfig/vmName.py
```

I think I didn't miss something in the usage of parameters into a pipeline. We can use a parameters value anywhere into a pipeline or a script using #{paramsvalue} right ?

How can I avoid the bash script to consider the # as a comment charactere ?

I tried using escape charactere like this : ``` \#{affiliate}``` but it doesn't work neither.

Maybe I missed something into the documentation regarding this subjects, but I still don't understand how to use it...

Thank you for your help
