### DISCUSSION TITLE
Artifact creation issue with API Call

### DISCUSSION THREAD

**Discussion by dauphinpasdroit** [gocd/gocd#11948] [Q&A] [answered]
Hey,

I encounter some issues with the artifact creation in a job using an API call. 

Here is the sample of API Query:

```
                    "stages": [
                      {
                        "name": "preconfig",
                        "fetch_materials": true,
                        "clean_working_directory": false,
                        "never_cleanup_artifacts": false,
                        "approval": {
                          "type": "success",
                          "allow_only_on_success" : false,
                          "authorization": {
                            "roles": [],
                            "users": []
                          }
                        },
                        "environment_variables": [],
                        "jobs": [
                          {
                            "name": "preConfig",
                            "run_instance_count": null,
                            "timeout": null,
                            "environment_variables": [],
                            "resources": [],
                            "tasks": [
                              {
                                "type": "exec",
                                "attributes": {
                                  "run_if": [
                                    "passed"
                                  ],
                                  "command":  "/bin/bash",
                                  "arguments" : [ "./pipelines/deployVm/windowsAzure/jobs/preConfig/preConfig.sh" ],
                                  "working_directory": null
                                }
                              }
                            ]
                          }
                        ]
                      },
                      {
                        "name": "infrastructureDeployment",
                        "fetch_materials": true,
                        "clean_working_directory": false,
                        "never_cleanup_artifacts": false,
                        "approval": {
                          "type": "success",
                          "allow_only_on_success" : false,
                          "authorization": {
                            "roles": [],
                            "users": []
                          }
                        },
                        "environment_variables": [],
                        "jobs": [
                          {
                            "name": "infrastructureDeployment",
                            "run_instance_count": null,
                            "timeout": null,
                            "environment_variables": [],
                            "resources": [],
                            "tasks": [
                              {
                                "type": "exec",
                                "attributes": {
                                  "run_if": [
                                    "passed"
                                  ],
                                  "command":  "/bin/bash",
                                  "arguments" : [ "./pipelines/deployVm/windowsAzure/jobs/infrastructureDeployment/terraform.sh" ],
                                  "working_directory": null
                                }
                              }
                            ],
                            "artifacts": [
                                {
                                  "type": "build",
                                  "source": "snake-3740-09042023354",
                                  "destination": "snake-3740-09042023354"
                                }   
                                ]
                            }
                            ]
                        },

```

Here is the error message:

```
[go] The rule [snake-3740-09042023354] cannot match any resource under [pipelines/snake-3740-09042023354]
[go] [go] Uploading finished. Failed to upload [snake-3740-09042023354].
```

Here is the server configuration for the artifact settings: 

![image](https://github.com/gocd/gocd/assets/110522034/a44ac752-1e6e-4420-829c-f4352ff51756)

I've mostly use the same settings in a configuration file and that's one works:

```
    stages:  
    - preconfig:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          preConfig:
            # elastic_profile_id: eaProd
            tasks:
            - exec:
                command: /bin/bash          
                arguments: 
                - ./pipelines/deployVm/windowsAzure/jobs/preConfig/preConfig.sh
                run_if: passed
    - infrastructureDeployment:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          infrastructureDeployment:
            artifacts:
            - build:
                source: vm_info
                destination: vm_info  
            # elastic_profile_id: eaProd
            tasks:
            - exec:
                command: /bin/bash          
                arguments: 
                - ./pipelines/deployVm/windowsAzure/jobs/infrastructureDeployment/terraform.sh
                run_if: passed

```

The only thing that change is the name of the artifact. Does the new name is too long ? Otherwise, I can't understand what am I doing wrong here.

Thank you for the help
