### ISSUE TITLE
How can I use "run_if" in a script task?

### ISSUE THREAD

**Issue by jhernandez-iriusrisk** [gocd/gocd#12826]
##### Issue Type

We are trying to use the feature "run_if" in a yaml pipeline in a task type "script", so GoCD is not accepting any value that we write in the yaml file. Please, find below my intention:

```
tasks:
  - script: 
      run_if: any
        |
         ... multiple lines script ...
```
So the plan is to use it in the same way that it is possible to use with task exec:

```
exec:
  run_if: any
```

Could you share more info? It is included in the github documentation, but there is no example of this. 
Thank you in advance.

**Comment by chadlwilson** [comment]
That doesn’t look like valid yaml which is presumably why it’s not accepting it.

The script tag is a special shorthand for a commonly used task plugin with default task options. If you want to set task options like that you need to use the verbose syntax as for other plugin based tasks as documented at https://github.com/tomzo/gocd-yaml-config-plugin?tab=readme-ov-file#script

```yaml
plugin:
  options:
    script: |
      #... multiple lines script ...
  run_if: any
  configuration:
    id: script-executor
    version: 1
```
