### ISSUE TITLE
Bug: Configuration repo requires auto_update: True

### ISSUE THREAD

**Issue by FredrikWendt** [gocd/gocd#3985]
#### Short version

In order to _reduce stress/load_ on our GitLab and GoCD servers, we want to get rid of all polling. Instead, we're trying to only use webhooks (result of `git push`) and the update material API (invoked from GitLab's system hook).  
Apart from reducing load, this also speeds things up as we don't need to wait for a poll before our changes are picked up and put to play.

In #1133 we got a great feature added to GoCD. However, it requires that the configuration repository is polled for updates. This prevents us from having a poll free GoCD server.

#### Longer version

I have a git repository, located at `/data/repos/repo_one.git`
In that repo, there's a folder called `pipelines` containing a file named `a-pipeline.gocd.yaml`. It contains:

```yaml
pipelines:
  a-pipeline:
    group: a-group
    materials:
      source:
        git: /data/repos/repo_one.git
        auto_update: false

    stages:
      - noop:
          tasks:
            - exec:
                command: /bin/true
```

Now, when adding the above repository as a configuration repository, like so:

```xml
    <config-repo pluginId="yaml.config.plugin" id="data-repos-repo_one">
      <git url="/data/repos/repo_one.git" />
    </config-repo>
```

... then the GoCD server will put up this error:

`Invalid Merged Configuration [Nov-06 21:30:31]  
1+ errors :: Material of type Git (/data/repos/repo_one.git) is specified as a configuration repository and pipeline material with disabled autoUpdate. All copies of this material must have autoUpdate enabled or configuration repository must be removed;; - Config-Repo: /data/repos/repo_one.git at feeddeafcafe443bean2e0bcabe4cab1ebeacda
`

This means that you can't have "self sustained" repos, where the repo itself describes how it should be "built".
