### ISSUE TITLE
Getting error "Pipeline “B” tries to fetch artifact from pipeline B when referring Upstream pipeline in template

### ISSUE THREAD

**Issue by harshadnarvekar** [gocd/gocd#4920]
##### Issue Type

- Bug Report

##### Summary:
My yaml pipeline B refers to a template (not yet migrated to yaml) and template in-turn refers to another pipeline A (Migrated and added in the same yaml). With this setup I am still getting an error "Pipeline “B” tries to fetch artifact from pipeline “A”

##### Environment
 Go Version: 18.6.0

##### Steps to Reproduce

1. Create 2 pipelines (A & B) in yaml. 
2. Create a template and refer/fetch artifact upstream pipeline A
3. Load the yaml file in config xml using yaml plugin
4. Get error "Pipeline “B” tries to fetch artifact from pipeline “A”"

##### Expected Results
Both pipelines should load 

##### Actual Results
Getting error "Pipeline “B” tries to fetch artifact from pipeline “A”"

##### Code snippets/Screenshots

Part of Config XML in GOCD

```
<config-repos>
    <config-repo pluginId="yaml.config.plugin" id="gocd-yaml-pipeline">
      <git url="git@github.test.comyaml-config.git" branch="anybranch" />
    </config-repo>
  </config-repos>



  <templates>
   <pipeline name="TemplateWhichRefersUpstreamPipeline">
      <stage name="Deploy">
        <approval type="manual" />
        <jobs>
          <job name="ECS">
            <tasks>
              <fetchartifact origin="gocd" srcfile="cluster_name.txt" dest="artifacts" pipeline="#{parameter_refered_in_template}" stage="Cluster" job="Create">
                <runif status="passed" />
              </fetchartifact>
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
  </templates>
```
Yaml file:
```

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#../environments.yaml                       +
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++

format_version: 2
#=========================================================
# Common environment variables
#=========================================================
common:
  default_region: &region
    region: 'ap-doesnotmate-2'
  docker_repo: &docker_repo
    DOCKER_REPO: 'example.repo.com'
  default_environment_variables: &default_environment_variables
    <<: *docker_repo
    <<: *region

#=========================================================
#  GoCD Environment definitions
#=========================================================

#=========================================================
  exampleapp-nonproduction: &exampleapp 
    environment_variables:
      <<: *default_environment_variables
      aws_profile: 'testprofile'
      
pipelines:  

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#..Pipeline which is refered in tempalte
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  "Pipeline-A-yaml":
    group: exampleapp-nonproduction
    << : *exampleapp
    materials:
      Deployment:
       git: git@github.example.com/test.git
       branch: master
       destination: deployment
    parameters: # list of parameters that can be configured for a pipeline
      ecs_cluster_home: test/exampleapp
    template: AnyExampleTemplate

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#..Pipeline which uses a tempalate (which is not converted into yaml)
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  "Pipeline-B-yaml":
    group: exampleapp-nonproduction
    << : *exampleapp
    materials:
      Deployment:
       git: git@github.example.com/test.git
       branch: master
       destination: deployment
    parameters: # list of parameters that can be configured for a pipeline
      app_home: test/example2app
      ecs_cluster_home: test/exampleapp
      parameter_refered_in_template: Pipeline-A-yaml
    template: TemplateWhichRefersUpstreamPipeline

```
