### ISSUE TITLE
Github webhooks do not work with github-pr and git-fb plugins

### ISSUE THREAD

**Issue by dziemba** [gocd/gocd#5328]
##### Issue Type

- Bug Report

##### Summary

When using github webhooks with GoCD, builds for github pull requests or feature branches do not get triggered.

##### Environment

- Linux / Debian Stretch / Java 8
- GoCD 18.10
- [gocd-build-github-pull-requests](https://github.com/ashwanthkumar/gocd-build-github-pull-requests): 1.3.5

##### Steps to Reproduce

0. Set up Github webhooks, as per documentation
1. Create an SCM in the XML config:
```xml
  <scm id="test-pr" name="test-pr">
      <pluginConfiguration id="github.pr" version="1" />
      <configuration>
        <property>
          <key>url</key>
          <value>git@github.some/test.git</value>
        </property>
      </configuration>
    </scm>
```
2. Create pipelines:
```yml
---
format_version: 2
pipelines:
  test-master:
    group: x
    materials:
      git:
        git: git@github.com:some/test.git
    stages: [...]
  test-pr:
    group: x
    materials:
      git:
        scm: test-pr
    stages: [...]
```
3. Push commits to master
4. Push commits to a branch, create a PR on github

(repeat with plugin id `git.fb` to test feature branch pushing instead of PRs)

##### Expected Results

The `test-master` pipeline builds when changes are pushed to master.
The `test-pr` pipeline builds when a PR is created / a feature branch is pushed/updated.

##### Actual Results
The `test-master` pipeline builds when changes are pushed to master (so webhooks work fine in general).
The `test-pr` never builds (only when pushing to master for the `git.fb` one)

##### Possible Fix

Some ideas:
- Incoming webhooks need to fetch/update all branches, not just the one specified in the hook.
- Not sure why feature branch builds don't work (maybe because the branch does not exist yet and is thus not updated?)
- Also receive PR webhooks (for PR building)
