### ISSUE TITLE
Export pipeline generates invalid yaml

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#6038]
##### Issue Type

bug

- Security issue? [**DO NOT** report it here. Use [hackerone](https://hackerone.com/gocd) or send a mail to support@thoughtworks.com]
- Bug Report
- Feature proposal
- Feature enhancement
- Documentation Report
- Question? [**DO NOT** ask it here. Ask in the [mailing list](https://groups.google.com/forum/#!forum/go-cd)].

##### Summary

While exporting a pipeline with external artifacts, the YAML for the artifact configuration section is malformed. 
```
.
.
artifacts:
            - external:
                id: frontend
                store_id: dockerhub
                configuration:
                  - key: BuildFile
                    value: artifact_info.json
.
.
```
Under configuration, currently the exported yaml has a list of values (preceeded with a -), whereas it should be a map. 

A valid version of this section of the yaml would look like:
```
.
.
artifacts:
            - external:
                id: frontend
                store_id: dockerhub
                configuration:
                    key: BuildFile
                    value: artifact_info.json
.
.
```
##### Steps to Reproduce
Create a pipeline with the following YAML, export to YAML and use it in a config repo. 
```
format_version: 3
pipelines:
  ci-build-and-test:
    group: demo
    label_template: ${COUNT}
    lock_behavior: none
    environment_variables:
      DOCKERHUB_ORG: gocddemo
    materials:
      git:
        git: https://github.com/gocd-demo/k8s-webinar.git
        shallow_clone: true
        auto_update: true
        branch: master
    stages:
    - defaultStage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          defaultJob:
            timeout: 0
            elastic_profile_id: demo-app
            artifacts:
            - external:
                id: frontend
                store_id: dockerhub
                configuration:
                  key: BuildFile
                  value: artifact_info.json
            tasks:
            - exec:
                arguments:
                - -c
                - docker build . --cache-from gocddemo/guestbook:latest -t gocddemo/guestbook:v${GO_PIPELINE_LABEL}
                  -t gocddemo/guestbook:latest
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                - create_json
                command: rake
                run_if: passed
```

**Comment by arvindsv** [comment]
@ankitsri11 Looking at [this](https://github.com/tomzo/gocd-yaml-config-plugin#external), won't a valid version of what you posted look like this instead?

```yaml
artifacts:
  - external:
      id: frontend
      store_id: dockerhub
      configuration:
          options:
              BuildFile: artifact_info.json
```
