### ISSUE TITLE
gocd-server container not running

### ISSUE THREAD

**Issue by papanito** [gocd/gocd#6105]
##### Issue Type
- Bug Report

##### Summary

I deploy the latest helm-chart 1.8.0 but the container does not really start up and stays in state `ContainerCreating`
```
NAME                                            READY     STATUS              RESTARTS   AGE
nomadic-anaconda-gocd-server-6b9d555c6d-nhnjz   0/1       ContainerCreating   0          19m
```

##### Environment

k8s v1.13.4 self-hosted with Rancher 2.0

###### Basic environment details

* Go Version: `19.2.0`

###### Additional Environment Details

N/A

##### Steps to Reproduce

1. run `helm install stable/gocd -f values.yaml -n gocd`

##### Expected Results
gocd-server starts successfully

##### Actual Results
gocd-server stays forever in state `ContainerCreating`

##### Possible Fix
N/A

##### Log snippets

k8s Events
```
Warning 	FailedScheduling 	pod has unbound immediate PersistentVolumeClaims (repeated 5 times) 	23 minutes ago
Normal 	Scheduled 	Successfully assigned gocd/nomadic-anaconda-gocd-server-6b9d555c6d-nhnjz to devs0250 	23 minutes ago
Normal 	Pulled 	Container image "gocd/gocd-server:v19.2.0" already present on machine 	23 minutes ago
Normal 	Created 	Created container 	23 minutes ago
Normal 	Started 	Started container 	23 minutes ago
```

##### Code snippets/Screenshots
N/A

##### Any other info
N/A

**Comment by papanito** [comment]
my `values.yaml`
```yaml
rbac:
  create: true
  apiVersion: v1beta1
  roleRef:

serviceAccount:
  create: true
  name:

server:
  enabled: true
  shouldPreconfigure: true
  preconfigureCommand:
    - "/bin/bash"
    - "/preconfigure_server.sh"
  image:
    repository: "gocd/gocd-server"
    tag:
    pullPolicy: "IfNotPresent"

  resources: {}

  initContainers: []

  restartPolicy: Always

  nodeSelector: {}

  affinity: {}

  healthCheck:
    initialDelaySeconds: 90
    periodSeconds: 15
    failureThreshold: 10
  env:
    goServerSystemProperties:
    extraEnvVars:
      - name: http_proxy
        value: http://proxy.intra:8080
      - name: https_proxy
        value: http://proxy.intra:8080
      - name: GOCD_PLUGIN_INSTALL_kubernetes-elastic-agents
        value: https://github.com/gocd/kubernetes-elastic-agents/releases/download/2.1.0-135/kubernetes-elastic-agent-2.1.0-135.jar
      - name: GOCD_PLUGIN_INSTALL_docker-registry-artifact-plugin
        value: https://github.com/gocd/docker-registry-artifact-plugin/releases/download/1.0.0-25/docker-registry-artifact-plugin-1.0.0-25.jar
  service:
    type: "NodePort"
    httpPort: 8153
    httpsPort: 8154
    nodeHttpPort:
    annotations:

  ingress:
    enabled: true
    annotations:
    tls:

  persistence:
    enabled: true
    accessMode: "ReadWriteOnce"

    existingClaim:

    pvSelector:
    name:
      dockerEntryPoint: goserver-vol
    subpath:
      godata: godata
      homego: homego
      dockerEntryPoint: scripts
    extraVolumes: []

    extraVolumeMounts: []

  hostAliases:

  security:
    ssh:
      enabled: false
      secretName: gocd-server-ssh

agent:
  serviceAccount:
    reuseTopLevelServiceAccount: false
    name:

  deployStrategy: {}
  image:
    repository: "gocd/gocd-agent-alpine-3.9"
    tag:
    pullPolicy: "IfNotPresent"
  env:
    goServerUrl:
    agentAutoRegisterEnvironemnts:
    agentAutoRegisterEnvironments:
    agentAutoRegisterHostname:
    goAgentSystemProperties:
    goAgentBootstrapperArgs:
    goAgentBootstrapperJvmArgs:
    extraEnvVars:
  persistence:
    enabled: false
    accessMode: "ReadWriteOnce"
    size: 1Gi

    existingClaim:
    pvSelector:

    name:
      dockerEntryPoint: goagent-vol
    subpath:
      homego: homego
      dockerEntryPoint: scripts

    extraVolumes: []

  initContainers: []

  restartPolicy: Always

  privileged: false

  healthCheck:
    enabled: false
    initialDelaySeconds: 60
    periodSeconds: 60
    failureThreshold: 60

  security:
    ssh:
      enabled: false
      secretName: gocd-agent-ssh

  resources: {}

  hostAliases:

  affinity: {}
```

**Comment by arvindsv** [comment]
It looks like something to do with PVCs. I'd look at whether setting `persistence` to `false` helps first, and then look at PVs. Based on this:

```
Warning FailedScheduling  pod has unbound immediate PersistentVolumeClaims (repeated 5 times) 	23 minutes ago
```

Maybe @ankitsri11 or @sheroy have ideas?

**Comment by varshavaradarajan** [comment]
@arvindsv, the next line says it successfully scheduled and assigned a volume. It's a warning and comes up every time I do helm install. It's normal. @papanito - have there been any restarts of the GoCD server? You can find that out with `kubectl get pod`

**Comment by papanito** [comment]
@varshavaradarajan no there are no restarts at all
```bash
$ kubectl get pod -n gocd
NAME                          READY     STATUS              RESTARTS   AGE
gocd-server-cc87586f9-x6hdj   0/1       ContainerCreating   0          18h
```

**Comment by varshavaradarajan** [comment]
@papanito - are there any errors in rancher logs? 
Also, have you allocated enough memory and CPU to the nodes running the docker containers? Rancher shows node status and pod distribution. 

I was able to successfully do helm install on rancher. Although I tried rancher with GKE. May be try purging this helm release and installing?

**Comment by papanito** [comment]
there is enough resources available. So I purged the helm deployment and the namespace
```bash
helm delete gocd --purge
release "gocd" deleted

kubectl delete namespace gocd
namespace "gocd" deleted
```
then newly deployed
```
helm install -n gocd stable/gocd -f .\values.dev.yaml --namespace gocd
```
same problem still

**Comment by papanito** [comment]
So, I've deployed gocd in a different cluster with default `values.yaml`. This fails with the expected errors in the log as we don't have direct access to github.com and thus require a proxy

```bash
/docker-entrypoint.sh: Creating directories and symlinks to hold GoCD configuration, data, and logs
$ mkdir /go-working-dir
$ chown go:go /go-working-dir
$ ln -sv /godata/artifacts /go-working-dir/artifacts
'/go-working-dir/artifacts' -> '/godata/artifacts'
$ chown go:go /go-working-dir/artifacts
$ ln -sv /godata/config /go-working-dir/config
'/go-working-dir/config' -> '/godata/config'
$ chown go:go /go-working-dir/config
$ ln -sv /godata/db /go-working-dir/db
'/go-working-dir/db' -> '/godata/db'
$ chown go:go /go-working-dir/db
$ ln -sv /godata/logs /go-working-dir/logs
'/go-working-dir/logs' -> '/godata/logs'
$ chown go:go /go-working-dir/logs
$ ln -sv /godata/plugins /go-working-dir/plugins
$ chown go:go /go-working-dir/plugins
'/go-working-dir/plugins' -> '/godata/plugins'
$ ln -sv /godata/addons /go-working-dir/addons
$ chown go:go /go-working-dir/addons
'/go-working-dir/addons' -> '/godata/addons'
$ install-gocd-plugins
$ curl --silent --location --fail --retry 3 https://github.com/gocd/docker-registry-artifact-plugin/releases/download/1.0.0-25/docker-registry-artifact-plugin-1.0.0-25.jar --output /godata/plugins/external/docker-registry-artifact-plugin.jar
/usr/local/sbin/install-gocd-plugins: cannot curl --silent --location --fail --retry 3 https://github.com/gocd/docker-registry-artifact-plugin/releases/download/1.0.0-25/docker-registry-artifact-plugin-1.0.0-25.jar --output /godata/plugins/external/docker-registry-artifact-plugin.jar
/docker-entrypoint.sh: cannot install-gocd-plugins
```
Now I delete the installation, add the proxy settings to the `values.yaml` and install gocd again. This fails again with the same error as above although the proxy variables are set
```
https_proxy 	http://proxy.intra:8080
http_proxy 	http://proxy.intra:8080
```
So
- the issue describe above occurs in one cluster, no clue what causes is nor how to debug
- the problem with ignoring the proxy env vars is another issue?

**Comment by papanito** [comment]
So. different approach: I've uploaded the required jar files into an internal available repo (Nexus) and added the config to the `values.yaml`, and removed the proxy config, thus having
```yaml
    extraEnvVars:
      - name: GOCD_PLUGIN_INSTALL_kubernetes-elastic-agents
        value: https://nexus.intra/repository/filerepo/gocd/docker-registry-artifact-plugin/1.0.0-25/docker-registry-artifact-plugin-1.0.0-25.jar
      - name: GOCD_PLUGIN_INSTALL_docker-registry-artifact-plugin
        value: https://nexus.intra/repository/filerepo/gocd/kubernetes-elastic-agents/2.1.0-135/kubernetes-elastic-agent-2.1.0-135.jar
````
However this does not work neither
```bash
 curl --silent --location --fail --retry 3 https://nexus.intra/repository/filerepo/gocd/kubernetes-elastic-agents/2.1.0-135/kubernetes-elastic-agent-2.1.0-135.jar --output /godata/plugins/external/docker-registry-artifact-plugin.jar

/usr/local/sbin/install-gocd-plugins: cannot curl --silent --location --fail --retry 3 https://nexus.intra/repository/filerepo/gocd/kubernetes-elastic-agents/2.1.0-135/kubernetes-elastic-agent-2.1.0-135.jar --output /godata/plugins/external/docker-registry-artifact-plugin.jar

/docker-entrypoint.sh: cannot install-gocd-plugins
``

**Comment by papanito** [comment]
Ok, some more pieces: The webproxy has a self-signed certificate which I mapped as follows:
```yaml
    extraVolumes:
      - name: mycerts
        secret:
          defaultMode: 420
          secretName: mycerts
    # server.persistence.extraVolumeMounts additional server volumeMounts
    extraVolumeMounts:
      - mountPath: /etc/ssl/certs/NOPRootCAG3.crt
        subPath: NOPRootCAG3.crt
        name: mycerts
      - mountPath: /etc/ssl/certs/NOPSubordinateCASystemG3.crt
        subPath: NOPSubordinateCASystemG3.crt
        name: mycerts
      - mountPath: /etc/ssl/certs/RootCAG2.crt
        subPath: RootCAG2.crt
        name: mycerts
      - mountPath: /etc/ssl/certs/RootCAG3.crt
        subPath: RootCAG3.crt
        name: mycerts
      - mountPath: /etc/ssl/certs/SubordinateCASystemG3.crt
        subPath: SubordinateCASystemG3.crt
        name: mycerts
```
However after some investigation I believe as [gocd uses alpine linux](https://github.com/gocd/docker-gocd-server/blob/master/Dockerfile) and simply mapping the certificates may not be enough to be picked up, I have to run `update-ca-certificates` as suggested [here](https://hackernoon.com/alpine-docker-image-with-secured-communication-ssl-tls-go-restful-api-128eb6b54f1f)
