### ISSUE TITLE
feature propsal - scan multiple branches

### ISSUE THREAD

**Issue by thatsk** [gocd/gocd#6123]
##### Issue Type
- Feature proposal

##### Summary
gocd config repositories should support regex for scanning multiple branches.

![image](https://user-images.githubusercontent.com/15324013/55874301-92b12c80-5baf-11e9-8a93-dd40dc27853a.png)

##### Environment
gocd  19.1.0

**Comment by arvindsv** [comment]
I've been playing around with an idea to support branches with pipelines as code, in my head. I'm putting it out there as a nascent idea to be shot down / improved.


Assumption 1: Some kind of plugin-level templating mechanism (as in https://github.com/gocd/gocd/issues/5675) exists in the config-repo plugins.

#### Setup:
1. Imagine a pipeline defined in YAML / JSON with a single material (for now).
2. Assume that the material is marked, in some way, to need support for branches.

#### Example:

```yaml
track_branches_for: https://www.github.com/gocd/gocd
  patterns: pull/.*/head

  template:
    {{ foreach branch in CONTEXT['branches'] }}
      pipeline-${branch}:
        tag: mytag1
        group: mygroup
        materials:
          mygit:
            git: https://www.github.com/gocd/gocd
            branch: ${branch}
        stages:
          - stage1:
            ...
          
      pipeline-downstream-${branch}:
        tag: mytag1
        group: mygroup
        materials:
          mygit:
            git: https://www.github.com/gocd/gocd
            branch: ${branch}
          myupstream:
            pipeline: pipeline-${branch}
            stage: stage1
        stages:
          mystage:
            ...
    {{ end }}
```

#### Work:
  - The plugin would need to be aware of this and be able to understand branches + filter them.
  - The plugin would need to provide that as context to the template (see assumption that there is a templating mechanism).
  - Depending on how it is implemented, once a PR is merged or a branch is deleted, the context won't include that branch and the pipeline automatically goes away from GoCD.

#### Benefits of this approach:

1. Flexibility: You can use this to build whole VSMs for branches, if you want.
2. Proper branch support: Unlike with branches and PRs using the GoCD PR plugin, there won't be only one pipeline across all branches.
3. With some appropriate use of a concept such as tags, etc. all pipelines tagged with the same "tag" can be shown together in a dashboard, for visualization reasons, to reduce the clutter of having some many pipelines per branch.
4. GoCD core does not need to change (introducing branch support in GoCD core introduces a can of worms - such as, what happens if there are multiple materials tracking branches, how do you templatize this properly, etc).

#### More considerations:
1. Cruft left behind in the DB, after pipeline goes away. Not much we can do with this.
2. Pipeline goes away once a branch is deleted / PR is merged. Maybe not ideal, but probably not a big deal in many cases.
