### ISSUE TITLE
Preflight check claims 'reference is not allowed'

### ISSUE THREAD

**Issue by sandro-h** [gocd/gocd#6566]
##### Issue Type

- Bug Report

##### Summary

When using the config repo preflight check API on a config that references a pipeline of a config *in a different source repository*, the check returns an error. When the server loads this config normally, it does not return this error and everything works.

##### Environment

GoCD server 19.4.0
YAML Configuration Plugin 0.10.2

##### Steps to Reproduce

1. In git repository **repo1** - which is a config repo on the GoCD server - create, commit and push a first config with a 1st pipeline:
```yaml
environments:
  default:
    pipelines:
      - repo1-pipeline
pipelines:
  repo1-pipeline:
      group: POC
      materials:
        git:
          git: ssh://git@git.company.com:7999/project/my-code-repo.git
      stages:
        - build:
            clean_workspace: yes
            jobs:
              build:
                artifacts:
                  - build:
                      source: foobar.txt
                      destination: foobar
                tasks:
                  - exec:
                      command: bash
                      arguments: [-c, "echo hello > foobar.txt"]
```
2. In a separate git repository **repo2** - which is a config repo on the GoCD server - create, commit and push a second config with a 2nd pipeline referring to the 1st pipeline from repo1:
```yaml
environments:
  default:
    pipelines:
      - repo2-pipeline
pipelines:
  repo2-pipeline:
      group: POC
      materials:
        git:
          git: ssh://git@git.company.com:7999/project/my-code-repo.git
        repo1-pipeline:
          pipeline: repo1-pipeline
          stage: build
      stages:
        - build:
            clean_workspace: yes
            jobs:
              build:
                tasks:
                  - fetch:
                      pipeline: repo1-pipeline
                      stage: build
                      job: build
                      source: foobar/foobar.txt
                      is_file: yes
```
3. Both these configs are correctly loaded by the server and the two pipelines work.
4. Without making any changes to the configs, try to validate the **repo2** config:
```bash
 curl "https://gocd.company.com:8154/go/api/admin/config_repo_ops/preflight?pluginId=yaml.config.plugin&repoId=repo2" \
      -k -u $USER \
      -H 'Accept: application/vnd.go.cd.v1+json' \
      -F 'files[]=@repo2.gocd.yaml'
```

##### Expected Results

The preflight validation succeeds.

##### Actual Results

The preflight validation fails with:
```json
{
  "errors" : [ "Dependency from pipeline defined in cruise-config.xml to pipeline defined in ssh://git@git.company.com:7999/project/repo1.git at 9de10567dc0308fdd5c3cc2a00c4af6063cf2115is not allowed", "\"repo2-pipeline :: build :: build\" tries to fetch artifact from job \"repo1-pipeline :: build :: build\" which is defined in ssh://git@git.company.com:7999/project/repo1.git at 9de10567dc0308fdd5c3cc2a00c4af6063cf2115 - reference is not allowed" ],
  "valid" : false
}
```

##### Any other info
I wonder if maybe the config being validated (repo2) is treated as *local* whereas the target config (repo1) is treated as *remote*. When the configs are normally loaded by the server, they're both treated as *remote*. That is just some guessing based on snooping around in the code.
