### ISSUE TITLE
Export pipeline generates invalid configuration when pipeline has external fetch artifact task configured

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#7377]
##### Issue Type

- Bug Report

##### Summary

Export Pipeline generates invalid pipeline configurations when the pipeline has fetch external artifact config.

###### Basic environment details

* Go Version: `19.11.0`

###### Additional Environment Details

**With the following fetch external artifact config:**
![Screen Shot 2019-12-05 at 11 01 17 AM](https://user-images.githubusercontent.com/15275847/70207186-02cc7e00-1750-11ea-9340-e5f19aac2d38.png)

**Yaml plugin generates:**
```yaml
- fetch:
    options:
      EnvironmentVariablePrefix: asdf
      SkipImagePulling: 'true'
    artifact_id: viraj
    pipeline: up42
    stage: up42_stage
    job: up42_job
    run_if: passed
```

**JSON plugin generates:**
```json
{
  "artifact_id": "viraj",
  "configuration": [
    {
      "key": "EnvironmentVariablePrefix",
      "value": "asdf"
    },
    {
      "key": "SkipImagePulling",
      "value": "true"
    }
  ],
  "pipeline": "up42",
  "stage": "up42_stage",
  "job": "up42_job",
  "run_if": "passed",
  "type": "fetch"
}
```
