### ISSUE TITLE
Config repository reports error

### ISSUE THREAD

**Issue by maheshmadpathi** [gocd/gocd#7522]
##### Issue Type
- Bug Report

##### Summary

`GoCD 19.12.0` reports an error `Environment variable 'EKS_CLUSTER' is defined more than once with different values` but there is only one value against the variable, we have an older version of `GoCD 19.7.0` which is also using same BitBucket repository and branch, also on same commit but doesn't report any error.

##### Environment
all

###### Basic environment details

* Go Version: `19.12.0`
* JAVA Version: `13.0.1`
* OS: `Linux 4.14.138-114.102.amzn2.x86_64`
* Browser vendor and version (if relevant): `Chrome`

##### Steps to Reproduce

1. Create a config repository with `YAML Configuration Plugin` and having variable `EKS_CLUSTER` value to be identical in all pipelines on `GoCD 19.12.0`
2. Check for below errors in Logs
``` 
jvm 1    | 2019-12-31 03:23:01,079 WARN  [124@MessageListener for ConfigMaterialUpdateListener] GoFileConfigDataSource:317 - Merged config update operation failed on LATEST 1 partials. Falling back to using LAST VALID 0 partials. Exception message was: Number of errors: 1+
jvm 1    | 1. Environment variable 'EKS_CLUSTER' is defined more than once with different values;; 
jvm 1    | 
jvm 1    | com.thoughtworks.go.config.exceptions.GoConfigInvalidMergeException: Number of errors: 1+
jvm 1    | 1. Environment variable 'EKS_CLUSTER' is defined more than once with different values;; 
jvm 1    | 
jvm 1    |      at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.validateCruiseConfig(MagicalGoConfigXmlLoader.java:139)
jvm 1    |      at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.preprocessAndValidate(MagicalGoConfigXmlLoader.java:126)
jvm 1    |      at com.thoughtworks.go.config.MagicalGoConfigXmlWriter.write(MagicalGoConfigXmlWriter.java:76)
jvm 1    |      at com.thoughtworks.go.config.GoFileConfigDataSource.configAsXml(GoFileConfigDataSource.java:534)
jvm 1    |      at com.thoughtworks.go.config.GoFileConfigDataSource.getUnmergedConfig(GoFileConfigDataSource.java:466)
jvm 1    |      at com.thoughtworks.go.config.GoFileConfigDataSource.trySavingConfig(GoFileConfigDataSource.java:450)
jvm 1    |      at com.thoughtworks.go.config.GoFileConfigDataSource.writeWithLock(GoFileConfigDataSource.java:311)
jvm 1    |      at com.thoughtworks.go.config.CachedGoConfig.writeWithLock(CachedGoConfig.java:154)
jvm 1    |      at com.thoughtworks.go.config.GoConfigDao.updateConfig(GoConfigDao.java:117)
jvm 1    |      at com.thoughtworks.go.server.service.GoConfigService.updateConfig(GoConfigService.java:307)
jvm 1    |      at com.thoughtworks.go.config.GoPartialConfig.updateConfig(GoPartialConfig.java:98)
jvm 1    |      at com.thoughtworks.go.config.GoPartialConfig.onSuccessPartialConfig(GoPartialConfig.java:80)
jvm 1    |      at com.thoughtworks.go.config.GoRepoConfigDataSource.notifySuccessListeners(GoRepoConfigDataSource.java:199)
jvm 1    |      at com.thoughtworks.go.config.GoRepoConfigDataSource.onCheckoutComplete(GoRepoConfigDataSource.java:168)
jvm 1    |      at com.thoughtworks.go.server.materials.ConfigMaterialUpdateListener.updateConfigurationFromCheckout(ConfigMaterialUpdateListener.java:102)
jvm 1    |      at com.thoughtworks.go.server.materials.ConfigMaterialUpdateListener.onMessage(ConfigMaterialUpdateListener.java:79)
jvm 1    |      at com.thoughtworks.go.server.materials.ConfigMaterialUpdateListener.onMessage(ConfigMaterialUpdateListener.java:37)
jvm 1    |      at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:84)
jvm 1    |      at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:64)
jvm 1    |      at java.base/java.lang.Thread.run(Unknown Source)
```
3. Create a config repository with `YAML Configuration Plugin` and having variable `EKS_CLUSTER` value to be identical in all pipelines on `GoCD 19.7.0`  using the same Git repo as Point-1
4. Compare the configs between two versions

##### Expected Results
The error shouldn't happen

##### Actual Results
Config repo doesn't work and pipeline don't get displayed.

##### Log snippets

I found couple of errors In logs, one is above mentioned at point-2, and the other is below

```
jvm 1    | 2019-12-31 03:23:01,223 INFO  [124@MessageListener for ConfigMaterialUpdateListener] GoConfigDao:125 - Config update request by anonymous is completed
jvm 1    | 2019-12-31 03:23:02,226 ERROR [qtp2109116135-27] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-31 03:23:09,908 ERROR [qtp2109116135-32] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-31 03:23:12,259 ERROR [qtp2109116135-41] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-31 03:23:19,947 ERROR [qtp2109116135-28] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-31 03:23:22,272 ERROR [qtp2109116135-29] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-31 03:23:29,983 ERROR [qtp2109116135-27] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-31 03:23:32,296 ERROR [qtp2109116135-33] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-31 03:23:40,014 ERROR [qtp2109116135-35] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-31 03:23:42,317 ERROR [qtp2109116135-29] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-31 03:23:45,482  INFO [161@MessageListener for ServerPingListener] p.c.g.c.e.k.c.g.c.e.KubernetesPlugin:72 [plugin-cd.go.contrib.elasticagent.kubernetes] - [refresh-pod-state] Pod information successfully synced. All(Running/Pending) pod count is 0.
jvm 1    | 2019-12-31 03:23:50,035 ERROR [qtp2109116135-32] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-31 03:23:52,340 ERROR [qtp2109116135-41] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-31 03:24:00,047 ERROR [qtp2109116135-37] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-31 03:24:02,372 ERROR [qtp2109116135-23] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-31 03:24:10,089 ERROR [qtp2109116135-32] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-31 03:24:12,405 ERROR [qtp2109116135-33] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-31 03:24:20,109 ERROR [qtp2109116135-35] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-31 03:24:22,435 ERROR [qtp2109116135-23] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-31 03:24:30,121 ERROR [qtp2109116135-31] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-31 03:24:32,455 ERROR [qtp2109116135-33] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-31 03:24:40,142 ERROR [qtp2109116135-28] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-31 03:24:42,484 ERROR [qtp2109116135-27] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-31 03:24:45,484  INFO [161@MessageListener for ServerPingListener] p.c.g.c.e.k.c.g.c.e.KubernetesPlugin:72 [plugin-cd.go.contrib.elasticagent.kubernetes] - [refresh-pod-state] Pod information successfully synced. All(Running/Pending) pod count is 0.
```

**Comment by GaneshSPatil** [comment]
Hi @maheshmadpathi,

I was unable to reproduce the issue with `YAML Configuration Plugin` and having variable `EKS_CLUSTER` value to be identical in 2 pipelines on `GoCD 19.12.0`.

<details><summary>YAML configurations used for testing</summary>
<p>

```yaml
format_version: 3
pipelines:
  pipeline1:
    group: first
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    environment_variables:
      EKS_CLUSTER: some-value
    materials:
      git:
        git: https://github.com/ganeshspatil/junk
        shallow_clone: false
        auto_update: true
        branch: master
        encrypted_password: AES:Cu5uRbHhCGay9flr2dvExw==:95t3dDpZcJmpFmYgLnPFZA==
    stages:
    - stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          job:
            timeout: 0
            tasks:
            - exec:
                command: ls
                run_if: passed
  pipeline2:
    group: first
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    environment_variables:
      EKS_CLUSTER: some-value
    materials:
      git:
        git: https://github.com/ganeshspatil/junk
        shallow_clone: false
        auto_update: true
        branch: master
        encrypted_password: AES:Cu5uRbHhCGay9flr2dvExw==:95t3dDpZcJmpFmYgLnPFZA==
    stages:
    - stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          job:
            timeout: 0
            tasks:
            - exec:
                command: ls
                run_if: passed
```

![Screen Shot 2019-12-31 at 10 05 09 AM](https://user-images.githubusercontent.com/15275847/71610230-3797ed80-2bb5-11ea-9e60-093dd16bfc9a.png)

</p>
</details>


Can you share your example YAML configuration where this issue could be reproduced? Please make sure you redact the sensitive information from the config.
