### ISSUE TITLE
When updating git material both username and password, agent fails to clone the material as authentication fails

### ISSUE THREAD

**Issue by patrijua** [gocd/gocd#8143]
##### Issue Type
- Bug Report

##### Summary

When updating git materials username and password to pipeline yaml, Go server successfully uses updated credentials but agent fails to clone the material as authentication fails

###### Basic environment details
```
* Go Version: `GoCD Version: 19.12.0
* Pipelines defined as code
* JAVA Version: 13.0.1
* Running in GKE
* Kubernetes Elastic Agent Plugin Version 3.4.0-196
* Agent base image gocd/gocd-agent-docker-dind:v20.1.0 where some extra tools installed. No persistent data.
```
##### Steps to Reproduce

1. Use for example Github repository as a source for materials for a pipeline. Have two pair of credentials (user1 and user2) which can access this repository. Configure pipeline to use credentials of user1.
2. Run pipeline to check it's working ok and successfully fetching materials also to agent
2. Change Github user1 password -> Pipeline fails to check material updates because invalid password.
3. Update BOTH username and password (user2 credentials) to pipeline yaml
3. Make some test commit to repository so GoCD should trigger the pipeline when detecting the commit

##### Expected Results
Using user2 credentials, GoCD should detect the commit on the repo and trigger the pipeline. Agent should clone the material successfully.

##### Actual Results
Using user2 credentials, GoCD successfully detects the commit on the repo and triggers the pipeline. However, spinned up agent fails to clone the material because authentication fails

##### Log snippets
```
l[go] Received request to create a pod for job JobIdentifier{pipelineName='credtest', pipelineCounter=6, pipelineLabel='6', stageName='handle_helmsman_docker_image', stageCounter='1', jobName='buildjob-docker-image', jobId=2,382} in cluster https://35.228.191.74 at 2020-05-13 13:06:28 +00:00
[go] Waiting to create agent pod.
[go] Creating pod: %s
[go] Agent pod %s created. Waiting for it to register to the GoCD server.
[go] Job Started: 2020-05-13 13:07:16 GMT

[go] Start to prepare credtest/6/handle_helmsman_docker_image/1/buildjob-docker-image on gocd-agent-bca532b0-0ca1-4b00-a271-7085b2138e90 [/go]
[go] Start to update materials.

[go] Start updating gitmaterialdir at revision 7e4f878f373a0f1df46451faf1ee1ef342290c20 from https://github.com/patrijua/credtest.git
STDERR: Cloning into '/go/pipelines/credtest/gitmaterialdir'...
STDERR: remote: Invalid username or password.
STDERR: fatal: Authentication failed for 'https://github.com/patrijua/credtest.git/'
Failed to run git clone command
```

##### Code snippets/Screenshots

Example yaml:
```
pipelines:
  credtest: # name of pipeline
    group: Microservices
    materials:
      servicegit: # name of material
        git: https://github.com/patrijua/credtest.git
        branch: master
        username: patrijua
        encrypted_password: AES:kznm3pZZrLXOKxKmB7Ow3w==:1aRbuIxYdG97eZWx/C7WIuLGwnVxLVPNOdDSAwLZinU=
        destination: gitmaterialdir
        auto_update: true
    stages:
      - somestage: # name of stage
          jobs:
            buildjob-docker-image: # name of job
              elastic_profile_id: basic
              tasks:
               - exec:
                   command: bash
                   working_directory: gitmaterialdir
                   arguments:
                    - "-c"
                    - "cat test.txt"
```
##### Any other info
Colleague reported that he has detected this same behaviour using v20.1.0 and dockerized static agents, so this does not seem to be related to elastic agents.

**Comment by arvindsv** [comment]
I tried this with a normal static agent and it worked fine. I also removed the static agent and created another one, and it still worked fine. I'll try it with GKE.

**Comment by arvindsv** [comment]
@patrijua I tried this on GKE and it worked fine. I did use slightly different versions which I will list here:

```
Environment: GKE - With k8s 1.14.10-gke.27
GoCD Version: 20.3.0 (11530-f54d0bae7a39fe7add5460f3f8676a7936abf698)
Kubernetes Elastic Agent Plugin Version: 3.4.0-196 (same as yours)
Agent image: gocd/gocd-agent-docker-dind:v20.3.0
```
Pod YAML:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: gocd-agent-{{ POD_POSTFIX }}
  labels:
    app: web
spec:
  serviceAccountName: default
  containers:
    - name: gocd-agent-container-{{ CONTAINER_POSTFIX }}
      image: gocd/gocd-agent-docker-dind:v20.3.0
      securityContext:
        privileged: true
```

My config repo commits can be seen here: https://github.com/arvindsv/test-config-repo/commits/master

I made sure to follow the steps as well as I understood them (including using a wrong password to reproduce step 3 in your list of steps).

I've deleted the cluster and all the credentials I used here, but I'm happy to bring them back up and check, if I've misunderstood any steps.
