### ISSUE TITLE
Artifact source path and whitelist doesn’t support "./abc.txt" but works with "abc.txt"

### ISSUE THREAD

**Issue by pPanda-beta** [gocd/gocd#8270]
##### Issue Type

- Bug Report
Or
- Documentation Report

##### Summary

Title is self-explanatory

##### Environment

Gocd on docker / k8s

###### Basic environment details

Server: gocd/gocd-server:v20.1.0
Agent: gocd/gocd-agent-docker-dind:v20.1.0

##### Steps to Reproduce

1. Use `./abc.txt` as artifact source

For whitelist

1. Use `./**/*`

##### Expected Results

It should detect the artifact or changes in whitelist

##### Actual Results

Both the cases it failed. For artifact logs is "Not found" ( ./abc.txt is not found but abc.txt is found 😠 ) 
For whitelist it doesn’t trigger the pipeline.

##### Any other info

# Why is it so important?

Consider the following pipeline yaml (IT IS NOT GOCD TEMPLATE - ITS YAML DARK MAGICS) : 

```
format_version: 5
common:

  # BEGIN TEMPLATE - DO NOT TOUCH

  base-repo: &base-repo
    repo:
      git: |
        #{git-repo}
      branch: |
        #{branch}
      whitelist:                                  ############ Look here
        - >
          #{working-dir}/**/*


  build-stage: &build-stage
    clean_workspace: true
    jobs:
      build_push:
        elastic_profile_id: ***********
        tasks:
          - exec:
              working_directory: |
                #{working-dir}
              command: /bin/sh
              arguments:
                - -c
                - >
                  docker-build-push.sh -i #{image-name} -t $GO_REVISION_REPO-$GO_PIPELINE_LABEL -e #{registry-alias} -- #{extra-build-args}
        artifacts:
          - build:                                   ############ And Look here
              source: #{working-dir}/application_tag.txt

  helm-init-deploy-tasks: &helm-init-deploy-tasks
    - exec:
        command: helm-init.sh
        arguments:
          - >
            #{env}
          - >
            #{cluster}
    - fetch: 
        is_file: true
        stage: build_push
        job: build_push
        source: #{working-dir}/application_tag.txt
        destination: |
          #{working-dir}/helm-charts/#{svc-name}/docker-image-tags
    - exec:
        working_directory: | 
          #{working-dir}
        run_if: any
        command: /bin/sh
        arguments:
          - -c
          - >
            helm-deploy.sh -r #{svc-name} -n #{namespace} -e #{env} -t $GO_REVISION_REPO-$GO_PIPELINE_LABEL -f ./helm-charts/#{svc-name}/#{value-file} -w 5m0s



  simple-build-push-pipeline: &pipeline-template
    materials:  *base-repo
    stages:
      - build_push: *build-stage
      - deploy:
          approval:
            type: manual
          clean_workspace: true
          jobs:
            helm_deploy:
              elastic_profile_id: ***********
              tasks:
                - *helm-init-deploy-tasks

  #END TEMPLATE

```

Now this is good, for a mono repo pattern, where working dir is a folder inside repo root.
But it can not be used for the code base lying outside on the repo root. 

```
repo_root
├── Dockerfile   <<<<<<<< THIS IS DIFFICULT AS working_dir="." is not working
├── service-1
│   └── Dockerfile
└── service-2
    └── Dockerfile

```
