### ISSUE TITLE
Tests tab shows wrong index.html

### ISSUE THREAD

**Issue by sandro-h** [gocd/gocd#8440]
##### Issue Type

- Bug Report

##### Summary

When (accidentally) uploading an HTML test report as a Test artifact, the "Tests" tab may display this test report instead of the generated test summary.

###### Basic environment details

* Go Version: 20.4
* JAVA Version: 13.0.2
* OS: Linux 3.10.0-1062.12.1.el7.x86_64
* Browser vendor and version (if relevant): Firefox 79

##### Steps to Reproduce

1. Create a pipeline that uploads an arbitrary index.html as a test artifact. Minimal YAML config to reproduce:
```yaml
  test-tab-bug-reproduce:
    group: POC
    materials:
      git:
        git: https://github.com/sandro-h/dummy.git
    stages:
      - build:
          clean_workspace: yes
          jobs:
            build:
              artifacts:
                - test:
                    source: build/html_report
              tasks:
                - exec:
                    command: bash
                    arguments: ["-c", "mkdir -p build/html_report && echo '<h1>My HTML report</h1>' > build/html_report/index.html"]
```
2. Run the pipeline, check the Tests tab.

##### Expected Results

The html report is ignored and the generated test summary is shown. I.e:
```
Tests run: 0 , Failures: 0 , Not run: 0 , Time: .000 seconds.
No Tests Run
This project doesn't have any tests
```

##### Actual Results
It will show the "My HTML report" index.html instead of the test summary.

##### Possible Fix
JobDetailPresentationModel should not do an arbitrary recursive search for index.html, but prefer the top-level generated index.html containing the test summary, or the result/index.html. That's my naive view of it, perhaps I miss use cases where a recursive search is necessary.

##### Code snippets/Screenshots

testouput file hierarchy:
![testoutput_hierarchy](https://user-images.githubusercontent.com/22613301/89771272-59206680-db00-11ea-87ec-86c2e7749160.png)

##### Any other info
It's possible this behavior depends on the OS on which GoCD runs, since the recursive file search gives no guarantees on ordering.

I realize this is not exactly a critical bug, and it can be resolved by changing the test artifact to a build artifact. Figured I'd report it anyway. It does lead to confusion for users of our GoCD instance, and in our particular case even to some additional bad effects because the Test tab loads the html report in a sandboxed iframe that causes our SSO solution to log you out (due to cookie behavior).
