### ISSUE TITLE
unlockWhenFinished behavior seems to be ignored

### ISSUE THREAD

**Issue by Diogomrol** [gocd/gocd#8442]
##### Issue Type

- Bug Report

##### Summary

Although a pipeline has _unlockWhenFinished_ behavior, a new instance is triggering while the previous one is still running. This didn't happen before upgrading to GoCD 20.5.0.

###### Basic environment details

* Go Version: 20.5.0
* JAVA Version: 13.0.2
* OS: Linux 3.10.0-1127.18.2.el7.x86_64

##### Steps to Reproduce

Have a pipeline with two stages, none of them manual, triggering automatically on SVN commits, and observe if when one instance gets to the second stage the next instance starts running.

##### Expected Results

Only one pipeline should be triggered at a time.

##### Actual Results

We have two instances of the pipeline running at the same time (although it looks like the oldest one is processed first, but if for some reason that happens it will be bad because we have an implicit dependency between stages).

##### Code snippets/Screenshots

Example of this happening:
![image](https://user-images.githubusercontent.com/9485620/89811938-4aa17180-db37-11ea-8fb3-55d3d12c64dd.png)

**Comment by maheshp** [comment]
@Diogomrol I was not able to reproduce this issue on GoCD 20.5.0 or the latest experimental GoCD 20.7.0. The pipeline were locked till all the stages were complete with the trigger buttons disabled. Once the last stage finished(in my case the stage failed) the pipelines were unlocked.

The config I used to reproduce,

<details>
  <summary>Sample Pipeline Config </summary>

     <pipeline name="up42" lockBehavior="unlockWhenFinished">
      <materials>
        <git url="/Users/maheshp/work/go/for_test" branch="test" />
      </materials>
      <stage name="Stage1">
        <jobs>
          <job name="job1">
            <tasks>
              <exec command="ls" />
            </tasks>
          </job>
        </jobs>
      </stage>
      <stage name="Stage2">
        <jobs>
          <job name="job1">
            <tasks>
              <exec command="bomb" />
            </tasks>
          </job>
          <job name="job2">
            <tasks>
              <exec command="sleep">
                <arg>100</arg>
              </exec>
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
</details>

I don't think anything has changed around pipeline locking in recent times. Can you please provide a sample config I can use to reproduce this issue.

**Comment by chadlwilson** [comment]
I've personally seen this a number of times on `20.1.0` however not been able to find a reliable reprod. I think in some limited cases there are race conditions that allow this to happen. Anecdotally, the cases I have usually noticed it have been after a GoCD maintenance mode and restart, however there is some possible bias there since after a restart one tends to be looking quite carefully at running builds to see that things are running smoothly.

**Comment by Vye** [comment]
I'm seeing this in GoCD Version: 20.9.0 (12335-cccb4960bde1166ccd79277093295ed5a18573ed).

My yaml config has:
```
format_version: 10
pipelines:
  ExampleDeployDev:
     group: ExampleGroup
     label_template: ${COUNT}
     lock_behavior: unlockWhenFinished
     display_order: -1
```
Some keys omitted for brevity.

Not sure if it happens in other scenarios but I got it when the secret management backend failed to connect.

**Comment by arvindsv** [comment]
I tried this with this config:

<details>
  <summary>GoCD Config</summary>

```xml
<?xml version="1.0" encoding="utf-8"?>
<cruise xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cruise-config.xsd" schemaVersion="139">
  <server agentAutoRegisterKey="63cea6a4-dc92-47c3-b724-11a5d00f24d3" webhookSecret="34d415e0-c77f-4ba5-8902-43e00179052a" serverId="99791ab5-1db5-4101-87b9-ebe2a3cd7dca" tokenGenerationKey="8ac1c5ad-6f08-45c6-a5d1-635c62236b00">
    <backup emailOnSuccess="true" emailOnFailure="true" />
    <artifacts>
      <artifactsDir>artifacts</artifactsDir>
    </artifacts>
  </server>
  <config-repos>
    <config-repo id="configRepo1" pluginId="yaml.config.plugin">
      <git url="file:///tmp/repo" />
      <rules>
        <allow action="refer" type="*">*</allow>
      </rules>
    </config-repo>
  </config-repos>
  <pipelines group="defaultGroup" />
</cruise>
```

</details>

<details>
  <summary>Pipeline YAML (Test1.gocd.yaml)</summary>

```yaml
format_version: 10
pipelines:
  Test1:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: -1
    materials:
      git-8483186:
        git: /tmp/my-code-repo
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - Stage1:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Job1:
            timeout: 0
            tasks:
            - exec:
                command: sleep
                arguments:
                - '30'
                run_if: passed
    - Stage2:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Job1:
            timeout: 0
            tasks:
            - exec:
                command: sleep
                arguments:
                - '120'
                run_if: passed
```

</details>

... and the behaviour seemed to work fine. The pipeline got locked, and even though I had made more commits, they happened sequentially.
