### ISSUE TITLE
Environment variables are case sensitive

### ISSUE THREAD

**Issue by phzietsman** [gocd/gocd#9330]
##### Issue Type
- Bug Report
##### Summary

I am managing a GoCD environments using config repositories using the yaml config plugin (https://github.com/tomzo/gocd-yaml-config-plugin).  

We are trying to add proxy variables here but are getting errors when we have both HTTP_PROXY and http_proxy in the configuration. The errors are:
```
environment variable 'http_proxy' is not unique for for environment 'myenv'.;;
environment variable 'HTTP_PROXY' is not unique for for environment 'myenv'.;;
```
##### Environment
The server is being run using the official docker image

###### Basic environment details

* Go Version: `21.2.0 (12498-16e1ac6956cd5177a99dc3fe33503661881c354f)`
* JAVA Version: `15.0.2`
* OS: `Linux 4.14.225-168.357.amzn2.x86_64`

##### Steps to Reproduce
1. Create a repo and define an environment in there
```yaml
format_version: 10
environments:
  myenv:
    environment_variables:
      HTTP_PROXY: something
      http_proxy: something
```
2.  Setup the repo as a config repo

##### Expected Results
It should create an environment (admin>environment) names `myenv` with both HTTP_PROXY and http_proxy in there

##### Actual Results
It returns an error about non unique variables
