### ISSUE TITLE
Disabling scheduling for Pipeline Material still schedules pipeline (sometimes)

### ISSUE THREAD

**Issue by badbort** [gocd/gocd#9870]
##### Summary

I'm encountering issues where a pipeline runs in response to a commit as expected, but triggers dependencies despite those defining this pipeline as "do not schedule". 

This pipeline contains common configuration and settings files and is I do not wish for it to trigger anything except the 'artifacting' pipeline.

![image](https://user-images.githubusercontent.com/4551792/141427193-081f2044-d9c5-4453-913d-a1904a964f01.png)

In the above image, the offending pipeline here is `Configuration`. This pipeline merely artifacts some settings files from a git repo.

As you can see in the image, I have disabled the scheduling for the next pipeline. We'll call that pipeline 'Project-A'. `Project-A` has a git material called `Client1`.

The bug I'm reporting is `Configuration` still triggers `Project-A`, but the behaviour is not consistent. There are many pipelines just like `Project-A` but for different projects and clients - just different content files. Some of these pipelines aren't triggered. 

Other things to note about the pipeline setup:
- Many projects are contained in this `Client1` repo, and there is a pipeline for each. e.g. `Project-B`, ect.. 
- Due to the above, each pipeline has its own content folder in the git repo, and the pipelines have a whitelist to match changes in their associated folder in `Client1`.  
  ![image](https://user-images.githubusercontent.com/4551792/141434832-ac95390b-2abd-42c4-abae-ce365b10e1f0.png)

The following image is a real world example of `Configuration` it triggering many pipelines and in all cases it has had scheduling disabled. I regularly have to play whack-a-mole:
![image](https://user-images.githubusercontent.com/4551792/141433943-a1d01bdc-68cb-475c-8c4d-237538f1df22.png)

The workaround I will be attempting for now was mentioned in another thread; remove the pipeline material and reference the git repo directly, with a blacklist that matches all files: **/*

What I think is happening is after `Configuration` completes it checks all dependent pipelines. This check on `Project-A` does not appear to obey the whitelist for `Client1`. Commits to  `Client1` do get filtered through the whitelist, but `Configuration` does not appear to.

I may abandon this intermediate artifacting pipeline if a direct git reference approach doesn't exhibit this triggering behaviour - so we will see.

**Comment by chadlwilson** [comment]
Are you able to clarify how you are confident that the _reason_ for the trigger is due to `Configuration` completing? i.e If you look on the dashboard do you see the Pipeline material for `Condfiguration` is Yellow/highlighted (this is the changed material) but the other materials are not?

![image](https://user-images.githubusercontent.com/29788154/141448593-b9e7fd84-312f-495d-9bab-144d4a5fd7a4.png)

Or the equivalent (subtle, undocumented) "information" icon on the stage details for one of these ones you cancelled:

![image](https://user-images.githubusercontent.com/29788154/141448730-0bc9c830-211f-4822-90bc-e50dc2d0a495.png)

Also, side note - which GoCD version is this? It looks older.

**Comment by badbort** [comment]
> Are you able to clarify how you are confident that the reason for the trigger is due to Configuration completing

Pretty certain. It's part of my procedure to check and swat pipelines after I commit to the Configuration repo.

The `ClientN` repositories contain 3d content which don't change that often. They are also config repos and contain .gocd.yaml pipelines. The whitelists just have 3d content filters

![image](https://user-images.githubusercontent.com/4551792/141452419-ff939318-35b8-46af-86ec-aac8a062a53d.png)
![image](https://user-images.githubusercontent.com/4551792/141452460-5d8ab1f3-119f-44f3-9ce2-94b326f52e79.png)
![image](https://user-images.githubusercontent.com/4551792/141452522-bf205a9a-4016-4565-9a49-4f7ee72e6a15.png)

**Comment by chadlwilson** [comment]
Yes, that `20.5.0` upgrade is a tougher one due to the db migrations.

I'm not aware of a specific bug that might have been fixed, but I am curious about the use of the `type: configrepo` syntactic sugar from the yaml plugin.

It's also detecting a change in that same repo. Would that change have normally passed the whitelist (noting that you have tried to disable auto_updates on that repo/material)

I think to figure out what is going on we might need to look at server logs when the `Configuration` pipeline completes to get more clues.

**Comment by arvindsv** [comment]
I wasn't able to reproduce this. Not sure I have the setup right.

<img width="1129" alt="2021_11_12_21-15-26" src="https://user-images.githubusercontent.com/172235/141535414-4c2fb185-9988-4fb1-b792-5e001be2b95c.png">

<img width="827" alt="2021_11_12_21-15-39" src="https://user-images.githubusercontent.com/172235/141535450-0a010386-57ab-4763-93b5-6ce1bec4adb2.png">

The above trigger happened properly on a commit to repo.2. A commit to repo.1 did not trigger the downstream pipeline. Might need a bit of your help to come up with a simplified case which reproduces your scenario.

This is the config I used:

```yaml
pipelines:
  upstream-pipeline-1:
    group: test
    materials:
      mygit:
        git: /tmp/repo.1
    stages:
      - stage1:
          jobs:
            job1:
              tasks:
               - exec:
                   command: echo
  downstream-pipeline-1:
    group: test
    materials:
      mygit:
        git: /tmp/repo.2
      upstream:
        ignore_for_scheduling: true
        pipeline: upstream-pipeline-1
        stage: stage1
    stages:
      - stage1a:
          jobs:
            job1a:
              tasks:
               - exec:
                   command: echo
                   arguments:
                    - "hello"
```

I see Chad noted the fact that you use `type: configrepo`. I'll try to set something up using that and see.

**Comment by arvindsv** [comment]
Taking notes as I try this. 

### 1. Everything is stable:

<img width="874" alt="2021_11_12_21-24-54" src="https://user-images.githubusercontent.com/172235/141536332-1ea761a9-169e-41b9-b8dc-bcdb082bd410.png">

<details>
  <summary>test.gocd.yaml in the config repo looks like this:</summary>

```yaml
pipelines:
  upstream-pipeline-1:
    group: test
    materials:
      mygit:
        git: /tmp/repo.1
    stages:
      - stage1:
          jobs:
            job1:
              tasks:
               - exec:
                   command: echo
  downstream-pipeline-1:
    group: test
    materials:
      models:
        type: configrepo
        shallow_clone: true
        auto_update: false
        whitelist:
          - downstream/down.gocd.yaml
      upstream:
        ignore_for_scheduling: true
        pipeline: upstream-pipeline-1
        stage: stage1
    stages:
      - stage1a:
          jobs:
            job1a:
              tasks:
               - exec:
                   command: echo
                   arguments:
                    - "hello"
```

</details>

<details>
  <summary>downstream/down.gocd.yaml in the config repo looks like this:</summary>

```yaml
pipelines:
  test:
    group: test
    materials:
      mygit:
        git: /tmp/repo.2
    stages:
      - stage1:
          jobs:
            job1:
              tasks:
               - exec:
                   command: echo
```

</details>

### 2. A commit to repo.2

I expect only the `test` pipeline triggers.

<img width="874" alt="2021_11_12_21-27-21" src="https://user-images.githubusercontent.com/172235/141536567-646a649a-2421-4303-bafd-952afd7b5c91.png">

That went as expected:

<img width="874" alt="2021_11_12_21-28-23" src="https://user-images.githubusercontent.com/172235/141536673-3fcf6613-c367-4fa1-af27-7dbff8d49bca.png">

Everything stable again.

### 3. A commit to repo.1

I expect only `upstream-pipeline-1` to trigger and then stop (not triggering `downstream-pipeline-1`).

<img width="874" alt="2021_11_12_21-30-26" src="https://user-images.githubusercontent.com/172235/141536909-0ad6bd4d-2db8-42ec-9700-1eeda49775cd.png">

Yes, that's fine. Everything stable again:

<img width="874" alt="2021_11_12_21-30-26" src="https://user-images.githubusercontent.com/172235/141536956-a60d1d36-213c-4af3-88c0-e0ea90cee86a.png">

### 4. A commit to the config repo itself - but not to an allow-listed file

I expected it to trigger nothing, due to the allow-list.

<img width="1408" alt="2021_11_12_21-34-23" src="https://user-images.githubusercontent.com/172235/141537302-16715e6c-c49e-48ca-9255-d9fdfc37996b.png">

But it triggered the downstream pipeline. **Is that the bug you're seeing?**

### 5. A commit to the config repo itself - but to an allow-listed file

I expect it to trigger the `downstream-pipeline-1`.

<img width="1408" alt="2021_11_12_21-38-59" src="https://user-images.githubusercontent.com/172235/141537855-d86b8ad8-0a8c-47d6-8833-926306a718d9.png">

Yes, that's correct.

<img width="1408" alt="2021_11_12_21-39-05" src="https://user-images.githubusercontent.com/172235/141537893-9a2fcf1b-b017-45cf-afce-c49ee2ab3d56.png">

### 6. Another commit to a non-allow-listed file (like in step 4)

I thought that the allow-list might now take effect. And it did. Nothing was triggered.

<img width="1408" alt="2021_11_12_21-40-13" src="https://user-images.githubusercontent.com/172235/141538016-6bf70a3c-aa67-495c-a48c-a827f365700b.png">

--------------------------

So, if step 4 is a reproduction of the bug, then the fact that the upstream pipeline has a "waiting" run which did not trigger a downstream pipeline line might _somehow_ be causing it to trigger the pipeline, when a related material has an allow-list which _should_ have prevented it from triggering.

Meaning: In step 4, the downstream pipeline should be checked against two materials (git commit with a non-allow-listed file changed, and a pipeline with an upstream run available but not allowed to be used due to the `ignore_for_scheduling` flag set to true. In this case, the pipeline should not be triggered. But is.

**Comment by arvindsv** [comment]
If that is really what is happening ... I'm not sure I know enough about that part of the code to fix it for sure. But, is adding a second stage to `upstream-pipeline-1` an option? In your case, a second stage to `Configuration` pipeline. Then the downstreams could depend on that second stage instead. That way, you control when you want to downstreams of `Configuration` to run, by triggering that manual gate.

<img width="866" alt="2021_11_12_21-54-48" src="https://user-images.githubusercontent.com/172235/141539102-751eda6a-a847-48f5-b35b-77c764a982b7.png">

In my tests, once I got a green "Stage 2", the bug shown in Step 4 earlier did not happen. The allowlist worked properly.


<details>
  <summary>test.gocd.yaml in the config repo looks like this:</summary>

```yaml
pipelines:
  upstream-pipeline-1:
    group: test
    materials:
      mygit:
        git: /tmp/repo.1
    stages:
      - stage1:
          jobs:
            job1:
              tasks:
               - exec:
                   command: echo
      - stage2:
          approval:
            type: manual
          jobs:
            job1:
              tasks:
               - exec:
                   command: echo

  downstream-pipeline-1:
    group: test
    materials:
      models:
        type: configrepo
        shallow_clone: true
        auto_update: false
        whitelist:
          - downstream/down.gocd.yaml
      upstream:
        ignore_for_scheduling: true
        pipeline: upstream-pipeline-1
        stage: stage2
    stages:
      - stage1a:
          jobs:
            job1a:
              tasks:
               - exec:
                   command: echo
                   arguments:
                    - "hello"
```

</details>
